### ISSUE TITLE
Avoid prepending a "/"

### ISSUE THREAD

**Issue by GENL** [touhidurabir/laravel-stub-generator#1]
Please avoid prepending the full path with a slash ("/"). It does not work on windows.

**Comment by touhidurabir** [comment]
@GENL thanks for reporting . can you make a pull request to handle this ?

**Comment by GENL** [comment]
Hi! Fixed here: https://github.com/touhidurabir/laravel-stub-generator/pull/3/commits/41659b523256e4ca6e8a59045b0794b656f62b76

**Comment by touhidurabir** [comment]
merged .
