### ISSUE TITLE
[Feature Request]: Please add support for Laravel 11

### ISSUE THREAD

**Issue by adiramardiani** [touhidurabir/laravel-stub-generator#10]
### Feature Description

Currently laravel is version 10, but soon will be release for laravel 11, can you add laravel 11 in illuminate/support ?

**Comment by touhidurabir** [comment]
Hello @adiramardiani , hopefully I will be able to update it at this coming weekend . But if you want, you can make a PR also to .

**Comment by binaryfire** [comment]
Hi @touhidurabir. Thanks for this great package! Laravel 11 is being released today. Would it be possible to bump the dependency versions?

**Comment by touhidurabir** [comment]
added Laravel 11  support by [laravel 11 support added and PHPUnit xml configuration update](https://github.com/touhidurabir/laravel-stub-generator/commit/98690f31f8d0ce88529105685824de15311ade15)

**Comment by binaryfire** [comment]
@touhidurabir Thank you!
