### ISSUE TITLE
Stub variable with space.

### ISSUE THREAD

**Issue by GENL** [touhidurabir/laravel-stub-generator#2]
Stub variable written like this must work `{{ name }}`. Currently only the format without space works: `{{name}}`.

**Comment by touhidurabir** [comment]
Thanks for reporting this . will push a change to handle that case asap .

**Comment by GENL** [comment]
Hi! Fixed here https://github.com/touhidurabir/laravel-stub-generator/pull/3/commits/28b700321b03102c9f193e6e0bea516e11767326

**Comment by touhidurabir** [comment]
merged .
