### ISSUE TITLE
Support for other file types

### ISSUE THREAD

**Issue by amirmasoud** [touhidurabir/laravel-stub-generator#4]
### Feature Description

It seems .php file extension has been hardcoded into the package. Although it seems to be able to handle other file types.hardcoded

I wanted to know if you are open to a PR for this fix as well.

### Is this feature valuable for other users as well and why?

Creating other file types such as yml can be useful.

**Comment by touhidurabir** [comment]
@amirmasoud I think that can be good feature addition to the package . feel free to make PR for this feature .

**Comment by amirmasoud** [comment]
Opened a PR for this. https://github.com/touhidurabir/laravel-stub-generator/pull/5
