### ISSUE TITLE
[Feature Request]: Allow for repeater placeholder

### ISSUE THREAD

**Issue by nicolasbinet** [touhidurabir/laravel-stub-generator#7]
### Feature Description

This would be useful for classes or templates where code is being repeated and placeholders non foreseeable.

**Comment by touhidurabir** [comment]
> code is being repeated and placeholders non foreseeable.

@nicolasbinet I am bit confused about the feature . Can you provide any pseudo code example and use can for it ?

**Comment by nicolasbinet** [comment]
@touhidurabir My idea was to support @repeat features in the stub file.

After some thoughts, we implemented it differently. We needed to create dynamic classes with multiple almost identical methods, based on a single template.
We created a specific template for the methods, that we looped through with your lib, saved `toString()`, concatenated the results, and replace in our code. Almost as simple.

Thanks for taking the time to answer this feature request. This can be closed if you wish.

**Comment by touhidurabir** [comment]
Thanks for the update .
