### ISSUE TITLE
[Feature Request]: add support for laravel 10

### ISSUE THREAD

**Issue by zofe** [touhidurabir/laravel-stub-generator#8]
### Feature Description

please add support for laravel 10 updating in "or" illuminate contracts, illuminate configs and php version

**Comment by MohammedElattar** [comment]
+1

**Comment by sim8568X** [comment]
I already created a pull request that added laravel 10 support. Waiting for accepting
[ the pull request ](https://github.com/touhidurabir/laravel-stub-generator/pull/9)

**Comment by touhidurabir** [comment]
Merged the PR . Thanks .

**Comment by sim8568X** [comment]
> Merged the PR . Thanks .

Thanks @touhidurabir for accepting
